#include "Order.h"

/**
 *  Represents a single order. This is the order's only instance in the program. The objects are referenced from here.
 */

/** 
 *  returns true if the order is a Buy order, false otherwise
 */
bool Order::isBuy()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-13-1-4137f8f2:129306551b9:-8000:000000000000123A begin
{
	return action == 'B';
}
// section -64--88-13-1-4137f8f2:129306551b9:-8000:000000000000123A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Order::display()
// section -64--88-1-100-12b48725:129324f236e:-8000:0000000000001295 begin
{
	printf("%08ld ", id);
	printf("%08ld ", timestamp);
	switch (type) {
	case 'M':
		printf("%c ", action);
		printf("Market (%4d)        ", vol);
		break;
	case 'L':
		printf("%c ", action);
		printf("Limit  (%4d,%5.1f) ", vol, (float) price1 / 10.0);
		break;
	case 'S':
		printf("%c ", action);
		printf("Stop   (%4d,%5.1f) ", vol, (float) price1 / 10.0);
		break;
	case 'T':
		printf("%c ", action);
		printf("StopLim(%4d,%5.1f,%5.1f) ", vol, (float) price1 / 10.0,
				(float) price2 / 10.0);
		break;
	case 'C':
		printf("* Cancel  %6ld        ", id);
		break;
	default:
		break;
	}
	printf("\n");
}
// section -64--88-1-100-12b48725:129324f236e:-8000:0000000000001295 end


